import { WarehouseDetail } from './warehouse-detail';

export interface StockItem {
  id: string;
  rowNumber: number;
  note: { value: string };
  ABCCode: Record<string, unknown>;
  AutoIncrementalValue: { value: string };
  AverageCost: { value: number };
  BaseUOM: { value: string };
  COGSAccount: { value: string };
  COGSSubaccount: { value: string };
  Content: Record<string, unknown>;
  CurrentStdCost: { value: number };
  DefaultIssueLocationID: Record<string, unknown>;
  DefaultPrice: { value: number };
  DefaultReceiptLocationID: Record<string, unknown>;
  DefaultWarehouseID: { value: string };
  Description: { value: string };
  DimensionVolume: { value: number };
  DimensionWeight: { value: number };
  DiscountAccount: Record<string, unknown>;
  DiscountSubaccount: Record<string, unknown>;
  ImageUrl: Record<string, unknown>;
  InventoryAccount: { value: string };
  InventoryID: { value: string };
  InventorySubaccount: { value: string };
  ItemClass: { value: string };
  ItemStatus: { value: string };
  ItemType: { value: string };
  LandedCostVarianceAccount: Record<string, unknown>;
  LandedCostVarianceSubaccount: Record<string, unknown>;
  LastCost: { value: number };
  LastModified: { value: string };
  LastStdCost: { value: number };
  LotSerialClass: { value: string };
  Markup: { value: number };
  MaxCost: { value: number };
  MinCost: { value: number };
  MinMarkup: { value: number };
  MSRP: { value: number };
  PackagingOption: { value: string };
  PackSeparately: { value: boolean };
  PendingStdCost: { value: number };
  POAccrualAccount: { value: string };
  POAccrualSubaccount: { value: string };
  PostingClass: { value: string };
  PriceClass: Record<string, unknown>;
  PriceManager: Record<string, unknown>;
  PriceWorkgroup: Record<string, unknown>;
  ProductManager: Record<string, unknown>;
  ProductWorkgroup: Record<string, unknown>;
  PurchasePriceVarianceAccount: { value: string };
  PurchasePriceVarianceSubaccount: { value: string };
  ReasonCodeSubaccount: { value: string };
  SalesAccount: { value: string };
  SalesSubaccount: { value: string };
  StandardCostRevaluationAccount: { value: string };
  StandardCostRevaluationSubaccount: { value: string };
  StandardCostVarianceAccount: { value: string };
  StandardCostVarianceSubaccount: { value: string };
  SubjectToCommission: { value: boolean };
  TaxCategory: { value: string };
  ValuationMethod: { value: string };
  VolumeUOM: Record<string, unknown>;
  WarehouseDetails: WarehouseDetail[];
  WeightUOM: Record<string, unknown>;
  custom: Record<string, unknown>;
  _links: {
    self: string;
    'files:put': string;
  };
}
